// This is the list of presets held by AoE4TargetFireTool's state
export const initialPreset = [
  {
    id: 0,
    trueId: crypto.randomUUID(),
    name: "Mangudai",
    damage: 5,
    attackSpeed: 0.88,
    health: 85,
    quantity: 7,
    range: 3.5,
    isPreset: true,
  },
  {
    id: 1,
    trueId: crypto.randomUUID(),
    name: "Archer",
    damage: 5,
    attackSpeed: 1.62,
    health: 70,
    quantity: 14,
    range: 5,
    isPreset: true,
  },
  {
    id: 2,
    trueId: crypto.randomUUID(),
    name: "Longbow",
    damage: 6,
    attackSpeed: 1.62,
    health: 70,
    quantity: 12,
    range: 7,
    isPreset: true,
  },
  {
    id: 3,
    trueId: crypto.randomUUID(),
    name: "House",
    damage: 1,
    attackSpeed: 1,
    health: 800,
    quantity: 1,
    range: 0,
    isPreset: true,
  },
];
