// This is the list of presets held by AoE4TargetFireTool's state
export const initialPreset = [
  {
    id: 0,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "Mangudai",
    damage: 5,
    attackSpeed: 0.88,
    health: 85,
    armor: 0,
    quantity: 7,
    range: 3.5,
  },
  {
    id: 1,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "Archer",
    damage: 5,
    attackSpeed: 1.62,
    health: 70,
    armor: 0,
    quantity: 14,
    range: 5,
  },
  {
    id: 2,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "Longbow",
    damage: 6,
    attackSpeed: 1.62,
    health: 70,
    armor: 0,
    quantity: 12,
    range: 7,
  },
  {
    id: 3,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "Javelin Thrower",
    damage: 12,
    attackSpeed: 2.12,
    health: 70,
    armor: 3,
    quantity: 9,
    range: 6,
  },
  {
    id: 4,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "Camel Archer",
    damage: 12,
    attackSpeed: 1.38,
    health: 140,
    armor: 0,
    quantity: 4,
    range: 3.75,
  },
  {
    id: 5,
    trueId: crypto.randomUUID(),
    isPreset: true,
    name: "House",
    damage: 1,
    attackSpeed: 1,
    health: 800,
    armor: 50,
    quantity: 1,
    range: 0,
  },
];
