/* export const exampleValues = {
  buildName: "presetMongol",
  currentStep: 1,
  food: 200,
  wood: 150,
  gold: 100,
  stone: 0,
  units: {
    villager: 6,
    trader: 0,
    fishingShip: 0,
    military: [{ name: "Khan", quantity: 1 }],
  },
  production: [
    { productionType: "LandmarkTownCenter", productionCall: TownCenter },
  ],
  goalUnits: { villager: 0, traders: 0, fishingShips: 0, military: [] },
  goalFood: 0,
  goalWood: 0,
  goalGold: 0,
  goalStone: 0,
  gatheringRatePerSecondFood: 0.6,
  gatheringRatePerSecondWood: 0.6,
  gatheringRatePerSecondGold: 0.6,
  gatheringRatePerSecondStone: 0.6,
  gatheringRateAveragePerMinFood: 37.5,
  gatheringRateAveragePerMinWood: 37.5,
  gatheringRateAveragePerMinGold: 37.5,
  gatheringRateAveragePerMinStone: 37.5,
  gatherRateBonusFood: 1,
  gatherRateBonusWood: 1,
  gatherRateBonusGold: 1,
  gatherRateBonusStone: 1,
  dropOffBonusFood: 1,
  dropOffBonusWood: 1,
  dropOffBonusGold: 1,
  dropOffBonusStone: 1,
  initialGameStartDelay: 3,
  villagerProducedInitialTravelDelay: 5,
  villagerDropOffDelay: 5,

  villagerProductionSpeed: 20,
  timer: 0,
  timerGoal: 0,
  villagerResourceSplitFood: 5,
  villagerResourceSplitWood: 0,
  villagerResourceSplitGold: 1,
  villagerResourceSplitStone: 0,

  tradeDurationOfTrip: 0,
  tradeResourceGainedFood: 0,
  tradeResourceGainedWood: 0,
  tradeResourceGainedGold: 0,
  tradeResourceGainedStone: 0,

  fishingDropOffDelay: 0,
  fishingGatherRateBonus: 1,
  fishingDropOffBonus: 1,

  productionQueuesActiveTownCenter: 1,
  productionQueuesActiveMarket: 0,
  productionQueuesActiveDock: 0,
  recordOfSavedSteps: [],
}; */

export const initialValues = {
  buildName: "presetMongol",
  curStep: 0,
  savedSteps: [],
  timer: 0,

  curFood: 200,
  curWood: 150,
  curGold: 100,
  curStone: 0,

  goalType: "No goal",
  goalName: null,
  goalFood: null,
  goalWood: null,
  goalGold: null,
  goalStone: null,
};
